# Generated by Django 5.1.3 on 2024-11-13 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0002_productos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='Categorias',
        ),
        migrations.AddField(
            model_name='productos',
            name='Categoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Libreria.categoria'),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
